version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:mac
    container_name: al-folio-website
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=6006 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 6006:6006
    volumes:
      - .:/srv/jekyll